services:
  venda_boa_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: venda_boa_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - venda_boa_network

  nginx:
    image: nginx:alpine
    container_name: venda_boa_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d
    networks:
      - venda_boa_network

  venda_boa_db:
    image: mysql:8.0
    container_name: venda_boa_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: venda_boa
      MYSQL_ROOT_PASSWORD: Nova_s3nh4_forte
    networks:
      - venda_boa_network

networks:
  venda_boa_network:
    driver: bridge
